version: "3.5"
services:
  backend:
    container_name: awesome_app
    working_dir: /var/www/awesomebackend
    build:
      context: .
    volumes:
      - .:/var/www/awesomebackend
      - /var/www/awesomebackend/node_modules
    ports:
      - 1108:3001
    networks:
      - awesomenet
    depends_on:
      - db

  db:
    image: postgres:11.5-alpine
    container_name: awesome_postgres
    networks:
      - awesomenet
    volumes:
      - /home/shohag/Workspace/Deploy/db_store/awesome:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=awesome
      - POSTGRES_PASSWORD=awesome
      - POSTGRES_DB=awesome

  db_client:
    image: adminer
    container_name: awesome_app_adminer
    ports:
      - 1109:8080
    depends_on:
      - db
    networks:
      - awesomenet

networks:
  awesomenet:
    driver: bridge
